---

Resources:

  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: guessthename.deploy.role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"
        - "arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS"

  EC2CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: guessthename.ec2.service.role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"

Outputs:
  CodeDeployRole:
    Value: !Ref CodeDeployRole
    Export:
      Name: "CodeDeployRole"
  EC2CodeDeployServiceRole:
    Value: !Ref EC2CodeDeployServiceRole
    Export:
      Name: "EC2CodeDeployServiceRole"
